# Server configuration
server:
  port: 8081
#  context-path: /micro

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8010/eureka/
  instance:
    prefer-ip-address: true
    
# Cloudant Confiugration for cloudant DB Nicroservices
cloudant:
  username: <username>
  password: <password>
  host: https://<hosturl>

spring:
  rabbitmq:
    host: <hosturl>
    port: <port>
    virtual-host: <>
    username: <username>
    password: <password>
