# Server configuration
server:
  port: 8082
#  context-path: /micro
management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    prefer-ip-address: true

# Cloudant Confiugration for cloudant DB Nicroservices
cloudant:
  username: <user>
  password: <pass>
  host: https://<url>
  
spring:
  rabbitmq:
    host: <url>
    port: <port>
    virtual-host: <>
    username: <user>
    password: <pass>
